/**
 * ai_image_alt/index.js - AI-Powered Image Alt Text Generation
 *
 * WHY THIS EXISTS:
 * Automatically generates accessible, descriptive alt text for images using AI providers.
 * Improves web accessibility compliance and reduces manual content entry burden.
 *
 * DESIGN DECISIONS:
 * - Integrates with AI registry to use configured providers
 * - Supports multiple AI providers with automatic fallback
 * - Includes quality scoring to ensure alt text meets WCAG standards
 * - Provides both service API and CLI interface
 * - Stores generation metadata for analytics
 *
 * USAGE:
 *   const altTextService = services.get('ai-alt-text');
 *   const result = await altTextService.generate(imagePath);
 *   const score = await altTextService.scoreQuality(altText);
 */

import { readFileSync, existsSync } from 'node:fs';
import { basename, extname, join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

// Get the directory of this module for loading templates
const __dirname = dirname(fileURLToPath(import.meta.url));

/**
 * Load a template file from this module's templates directory
 */
function loadTemplate(name) {
  const templatePath = join(__dirname, 'templates', name);
  return readFileSync(templatePath, 'utf-8');
}

/**
 * Redirect helper
 */
function redirect(res, url) {
  res.writeHead(302, { 'Location': url });
  res.end();
}

/**
 * Parse URL-encoded form data from request body
 */
function parseFormBody(req) {
  return new Promise((resolve, reject) => {
    let body = '';

    req.on('data', chunk => {
      body += chunk.toString();
      if (body.length > 1024 * 1024) {
        reject(new Error('Form data too large'));
      }
    });

    req.on('end', () => {
      try {
        const data = {};
        const pairs = body.split('&');

        for (const pair of pairs) {
          const [key, value] = pair.split('=').map(s => decodeURIComponent(s.replace(/\+/g, ' ')));
          if (key) {
            // Handle arrays (multiple values with same key)
            if (data[key]) {
              if (Array.isArray(data[key])) {
                data[key].push(value || '');
              } else {
                data[key] = [data[key], value || ''];
              }
            } else {
              data[key] = value || '';
            }
          }
        }

        resolve(data);
      } catch (error) {
        reject(new Error('Invalid form data'));
      }
    });

    req.on('error', reject);
  });
}

/**
 * Service state
 */
let services = null;

/**
 * Supported image formats
 */
const SUPPORTED_FORMATS = ['jpg', 'jpeg', 'png', 'gif', 'webp'];
const MAX_IMAGE_SIZE = 10 * 1024 * 1024; // 10MB

/**
 * Initialize the alt text generation service
 */
export function hook_boot(context) {
  services = context.services;

  // Register the alt text service
  services.register('ai-alt-text', () => ({
    generate: generateAltText,
    scoreQuality: scoreAltTextQuality,
    bulk: bulkGenerate
  }));

  // Enhance image field widget with AI alt text capabilities
  const fieldRegistry = services.get('field-registry');
  if (fieldRegistry) {
    enhanceImageWidget(fieldRegistry, services);
  } else {
    console.warn('[ai_image_alt] Field registry not available, widget enhancement skipped');
  }

  console.log('[ai_image_alt] Alt text generation service loaded');
}

/**
 * Register API routes
 */
export function hook_routes(register, context) {
  // GET /admin/config/ai/alt-text - Admin settings form
  register('GET', '/admin/config/ai/alt-text', async (req, res) => {
    try {
      // Load current settings from config file
      let settings = {
        primaryProvider: 'ai_test',
        fallbackProviders: [],
        qualityThreshold: 70,
        autoGenerateDefault: false,
        rateLimitPerUser: 100,
        systemPrompt: 'Generate concise, descriptive alt text for this image. Follow WCAG accessibility guidelines. Be specific, avoid generic phrases like \'image of\' or \'picture of\'. Describe what the image shows, not its technical properties. Keep it under 125 characters when possible.'
      };

      // Try to load from config file
      try {
        const configPath = join(process.cwd(), 'config', 'ai_image_alt.json');
        if (existsSync(configPath)) {
          const configData = readFileSync(configPath, 'utf-8');
          settings = JSON.parse(configData);
        }
      } catch (err) {
        // Use defaults if config file doesn't exist or is invalid
        console.log('[ai_image_alt] Using default settings:', err.message);
      }

      // Get available AI providers
      const aiRegistry = context.services.get('ai-registry');
      const providers = aiRegistry.getByType('provider');

      // Get CSRF token
      const auth = context.services.get('auth');
      const csrfToken = auth.getCSRFToken(req);

      // Parse flash messages from query string
      const urlObj = new URL(req.url, 'http://localhost');
      const success = urlObj.searchParams.get('success');
      const error = urlObj.searchParams.get('error');
      let flash = null;
      if (success) {
        flash = { type: 'success', message: decodeURIComponent(success) };
      } else if (error) {
        flash = { type: 'error', message: decodeURIComponent(error) };
      }

      // Load and render template with simple string replacement
      let html = loadTemplate('settings-simple.html');

      // Flash message
      if (flash) {
        const flashHtml = `<div class="alert alert-${flash.type}">${flash.message}</div>`;
        html = html.replace('__FLASH__', flashHtml);
      } else {
        html = html.replace('__FLASH__', '');
      }

      // Provider dropdown options
      let providerOptions = '<option value="">-- Select Provider --</option>\n';
      for (const provider of providers) {
        const selected = provider.name === settings.primaryProvider ? 'selected' : '';
        const status = provider.status ? `(${provider.status})` : '';
        providerOptions += `<option value="${provider.name}" ${selected}>${provider.name} ${status}</option>\n`;
      }
      html = html.replace('__PROVIDERS__', providerOptions);

      // Fallback provider checkboxes
      let fallbackHtml = '';
      for (const provider of providers) {
        const checked = settings.fallbackProviders && settings.fallbackProviders.includes(provider.name) ? 'checked' : '';
        fallbackHtml += `<div class="checkbox-item">
<input type="checkbox" name="fallbackProviders" value="${provider.name}" id="fallback_${provider.name}" ${checked}>
<label for="fallback_${provider.name}">${provider.name}</label>
</div>\n`;
      }
      html = html.replace('__FALLBACK__', fallbackHtml);

      // Settings values
      html = html.replace('__QUALITY__', settings.qualityThreshold);
      html = html.replace('__RATELIMIT__', settings.rateLimitPerUser);
      html = html.replace('__PROMPT__', settings.systemPrompt || '');
      html = html.replace('__AUTO_CHECK__', settings.autoGenerateDefault ? 'checked' : '');
      html = html.replace('__CSRF__', csrfToken);

      res.writeHead(200, { 'Content-Type': 'text/html' });
      res.end(html);
    } catch (error) {
      console.error('[ai_image_alt] Settings form error:', error);
      res.writeHead(500, { 'Content-Type': 'text/plain' });
      res.end('Error loading settings form');
    }
  });

  // POST /admin/config/ai/alt-text - Save settings
  register('POST', '/admin/config/ai/alt-text', async (req, res) => {
    try {
      // Parse form data
      const formData = await parseFormBody(req);

      // Validate primary provider
      if (!formData.primaryProvider) {
        redirect(res, '/admin/config/ai/alt-text?error=' + encodeURIComponent('Primary provider is required'));
        return;
      }

      // Validate quality threshold (must be 0-100)
      const qualityThreshold = parseInt(formData.qualityThreshold, 10);
      if (isNaN(qualityThreshold) || qualityThreshold < 0 || qualityThreshold > 100) {
        redirect(res, '/admin/config/ai/alt-text?error=' + encodeURIComponent('Quality threshold must be between 0 and 100'));
        return;
      }

      // Validate rate limit (must be > 0)
      const rateLimitPerUser = parseInt(formData.rateLimitPerUser, 10);
      if (isNaN(rateLimitPerUser) || rateLimitPerUser <= 0) {
        redirect(res, '/admin/config/ai/alt-text?error=' + encodeURIComponent('Rate limit must be greater than 0'));
        return;
      }

      // Parse fallback providers (checkbox array)
      let fallbackProviders = [];
      if (formData.fallbackProviders) {
        fallbackProviders = Array.isArray(formData.fallbackProviders)
          ? formData.fallbackProviders
          : [formData.fallbackProviders];
      }

      // Build settings object
      const settings = {
        primaryProvider: formData.primaryProvider,
        fallbackProviders,
        qualityThreshold,
        autoGenerateDefault: formData.autoGenerateDefault === 'on',
        rateLimitPerUser,
        systemPrompt: formData.systemPrompt || ''
      };

      // Write to disk
      const { writeFileSync } = await import('node:fs');
      const configPath = join(process.cwd(), 'config', 'ai_image_alt.json');
      writeFileSync(configPath, JSON.stringify(settings, null, 2), 'utf-8');

      // Redirect with success message
      redirect(res, '/admin/config/ai/alt-text?success=' + encodeURIComponent('Settings saved successfully'));
    } catch (error) {
      console.error('[ai_image_alt] Save settings error:', error);
      redirect(res, '/admin/config/ai/alt-text?error=' + encodeURIComponent('Error saving settings: ' + error.message));
    }
  });

  // POST /api/ai/alt-text/generate - Generate alt text for an uploaded image
  // REQUIRES: Authentication (session or API token)
  // RATE LIMIT: 100 requests per hour per user
  register('POST', '/api/ai/alt-text/generate', async (req, res) => {
    const startTime = Date.now();

    try {
      // ========================================
      // STEP 1: AUTHENTICATION
      // ========================================
      const auth = context.services.get('auth');
      const session = auth.getSession(req);

      // Check session authentication
      if (!session || !session.userId) {
        // Try API token authentication (Authorization: Bearer <token>)
        const authHeader = req.headers['authorization'];
        if (!authHeader || !authHeader.startsWith('Bearer ')) {
          res.writeHead(401, { 'Content-Type': 'application/json' });
          res.end(JSON.stringify({
            error: 'Unauthorized',
            message: 'Authentication required. Provide session cookie or Authorization: Bearer <token> header.'
          }));
          return;
        }

        const token = authHeader.substring(7); // Remove 'Bearer '
        const content = context.services.get('content');

        // Verify API token
        const tokens = content.list('apitoken').items || [];
        const validToken = tokens.find(t => t.token === token);

        if (!validToken) {
          res.writeHead(401, { 'Content-Type': 'application/json' });
          res.end(JSON.stringify({
            error: 'Unauthorized',
            message: 'Invalid API token'
          }));
          return;
        }

        // Set userId from token for rate limiting
        session.userId = validToken.userId;
      }

      const userId = session.userId;

      // ========================================
      // STEP 2: RATE LIMITING
      // ========================================
      const ratelimit = context.services.get('ratelimit');
      const rateLimitKey = `ai-alt-text:${userId}`;
      const rateLimitResult = ratelimit.checkLimit(rateLimitKey, {
        points: 100,          // 100 requests
        duration: 3600,       // per hour (3600 seconds)
        reason: 'ai-alt-text'
      });

      if (!rateLimitResult.allowed) {
        const retryAfter = rateLimitResult.retryAfter || 60;
        res.writeHead(429, {
          'Content-Type': 'application/json',
          'X-RateLimit-Limit': '100',
          'X-RateLimit-Remaining': '0',
          'X-RateLimit-Reset': rateLimitResult.resetAt ? Math.floor(rateLimitResult.resetAt / 1000) : '',
          'Retry-After': retryAfter.toString()
        });
        res.end(JSON.stringify({
          error: 'Too Many Requests',
          message: 'Rate limit exceeded. Maximum 100 requests per hour.',
          retryAfter: retryAfter,
          limit: 100,
          resetAt: rateLimitResult.resetAt
        }));
        return;
      }

      // Add rate limit headers to success response
      const rateLimitHeaders = {
        'X-RateLimit-Limit': '100',
        'X-RateLimit-Remaining': rateLimitResult.remaining.toString(),
        'X-RateLimit-Reset': rateLimitResult.resetAt ? Math.floor(rateLimitResult.resetAt / 1000).toString() : ''
      };

      // ========================================
      // STEP 3: PARSE AND VALIDATE INPUT
      // ========================================
      // Parse multipart form data
      const formData = await parseMultipartFormData(req);

      if (!formData.file) {
        res.writeHead(400, {
          'Content-Type': 'application/json',
          ...rateLimitHeaders
        });
        res.end(JSON.stringify({
          error: 'Bad Request',
          message: 'No image file provided. Send image as multipart/form-data with field name "file".'
        }));
        return;
      }

      // ========================================
      // STEP 4: SAVE TEMP FILE
      // ========================================
      const { writeFileSync, mkdirSync } = await import('node:fs');
      const { join } = await import('node:path');
      const tmpDir = '/tmp/claude/ai-alt-text';

      if (!existsSync(tmpDir)) {
        mkdirSync(tmpDir, { recursive: true });
      }

      const tmpPath = join(tmpDir, formData.file.filename);
      writeFileSync(tmpPath, formData.file.data);

      // ========================================
      // STEP 5: GENERATE ALT TEXT
      // ========================================
      const result = await generateAltText(tmpPath, context.services);

      // Clean up temp file
      const { unlinkSync } = await import('node:fs');
      unlinkSync(tmpPath);

      // ========================================
      // STEP 6: LOG API USAGE FOR ANALYTICS
      // ========================================
      const processingTime = Date.now() - startTime;

      // Log usage (you can enhance this to store in database)
      console.log(`[ai_image_alt] API usage - User: ${userId}, File: ${formData.file.filename}, Time: ${processingTime}ms, Score: ${result.qualityScore}/100`);

      // ========================================
      // STEP 7: RETURN ENHANCED RESPONSE
      // ========================================
      res.writeHead(200, {
        'Content-Type': 'application/json',
        ...rateLimitHeaders
      });

      res.end(JSON.stringify({
        success: true,
        data: {
          text: result.altText,
          score: result.qualityScore,
          confidence: result.confidence,
          processingTime: processingTime,
          metadata: {
            provider: result.provider,
            grade: result.qualityGrade,
            timestamp: result.timestamp
          }
        },
        rateLimit: {
          limit: 100,
          remaining: rateLimitResult.remaining,
          resetAt: rateLimitResult.resetAt
        }
      }));
    } catch (error) {
      console.error('[ai_image_alt] Generate error:', error);

      // Determine error type and status code
      let statusCode = 500;
      let errorMessage = error.message;

      if (error.message.includes('Unsupported image format')) {
        statusCode = 400;
      } else if (error.message.includes('Image too large')) {
        statusCode = 400;
      } else if (error.message.includes('not found')) {
        statusCode = 400;
      }

      res.writeHead(statusCode, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({
        error: statusCode === 400 ? 'Bad Request' : 'Internal Server Error',
        message: errorMessage
      }));
    }
  });

  // POST /api/ai/alt-text/score - Score alt text quality
  register('POST', '/api/ai/alt-text/score', async (req, res) => {
    try {
      const body = await parseJsonBody(req);

      if (!body.altText) {
        res.writeHead(400, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ error: 'Alt text is required' }));
        return;
      }

      const result = await scoreAltTextQuality(body.altText);

      res.writeHead(200, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify(result));
    } catch (error) {
      console.error('[ai_image_alt] Score error:', error);
      res.writeHead(500, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ error: error.message }));
    }
  });
}

/**
 * Inject widget client script into admin pages
 */
export function hook_admin_assets(context) {
  return {
    scripts: [widgetClientScript]
  };
}

/**
 * Parse JSON request body
 */
function parseJsonBody(req) {
  return new Promise((resolve, reject) => {
    let body = '';
    req.on('data', chunk => {
      body += chunk.toString();
    });
    req.on('end', () => {
      try {
        resolve(JSON.parse(body));
      } catch (e) {
        reject(new Error('Invalid JSON'));
      }
    });
    req.on('error', reject);
  });
}

/**
 * Parse multipart form data (simplified - handles single file upload)
 */
function parseMultipartFormData(req) {
  return new Promise((resolve, reject) => {
    const boundary = req.headers['content-type']?.split('boundary=')[1];
    if (!boundary) {
      reject(new Error('No boundary found'));
      return;
    }

    const chunks = [];
    req.on('data', chunk => chunks.push(chunk));
    req.on('end', () => {
      const buffer = Buffer.concat(chunks);
      const parts = [];
      const boundaryBuffer = Buffer.from(`--${boundary}`);

      let start = 0;
      while (true) {
        const idx = buffer.indexOf(boundaryBuffer, start);
        if (idx === -1) break;

        const nextIdx = buffer.indexOf(boundaryBuffer, idx + boundaryBuffer.length);
        if (nextIdx === -1) break;

        const part = buffer.slice(idx + boundaryBuffer.length, nextIdx);
        parts.push(part);
        start = nextIdx;
      }

      const result = {};
      for (const part of parts) {
        const headerEnd = part.indexOf('\r\n\r\n');
        if (headerEnd === -1) continue;

        const headers = part.slice(0, headerEnd).toString();
        const data = part.slice(headerEnd + 4, part.length - 2);

        const nameMatch = headers.match(/name="([^"]+)"/);
        const filenameMatch = headers.match(/filename="([^"]+)"/);

        if (nameMatch) {
          const name = nameMatch[1];
          if (filenameMatch) {
            result[name] = {
              filename: filenameMatch[1],
              data
            };
          } else {
            result[name] = data.toString();
          }
        }
      }

      resolve(result);
    });
    req.on('error', reject);
  });
}

/**
 * Register CLI commands
 */
export function hook_cli(register, context) {
  // Generate alt text for a single image
  register('ai:alt:generate', async (args, ctx) => {
    const imagePath = args[0];

    if (!imagePath) {
      console.error('Error: Image path is required');
      console.log('Usage: node index.js ai:alt:generate <image-path>');
      return;
    }

    try {
      console.log(`\nGenerating alt text for: ${imagePath}`);
      const result = await generateAltText(imagePath, ctx.services);

      console.log('\nResult:');
      console.log(`  Alt Text: ${result.altText}`);
      console.log(`  Confidence: ${(result.confidence * 100).toFixed(1)}%`);
      console.log(`  Provider: ${result.provider}`);
      console.log(`  Quality Score: ${result.qualityScore}/100`);

      if (result.qualityFeedback && result.qualityFeedback.length > 0) {
        console.log('\nQuality Feedback:');
        result.qualityFeedback.forEach(feedback => {
          console.log(`  - ${feedback}`);
        });
      }
      console.log('');
    } catch (error) {
      console.error(`Error: ${error.message}`);
    }
  }, 'Generate alt text for an image using AI');

  // Bulk generate alt text for media entities in database
  register('ai:alt:bulk', async (args, ctx) => {
    // Parse command line flags
    const flags = parseFlags(args);
    const { 'content-type': contentType, field, since, limit, 'dry-run': dryRun, resume } = flags;

    try {
      const results = await bulkGenerateFromDatabase({
        contentType,
        field,
        since,
        limit,
        dryRun,
        resume,
        services: ctx.services
      });

      console.log('\n' + '='.repeat(60));
      console.log('Bulk Alt Text Generation Complete');
      console.log('='.repeat(60));
      console.log(`  Total Processed: ${results.processed}`);
      console.log(`  Successful: ${results.success}`);
      console.log(`  Failed: ${results.failed}`);
      console.log(`  Skipped: ${results.skipped}`);

      if (dryRun) {
        console.log(`\n  [DRY RUN MODE - No changes saved]`);
      }

      if (results.errors.length > 0) {
        console.log('\nErrors:');
        results.errors.slice(0, 10).forEach(err => {
          console.log(`  - ${err.id}: ${err.error}`);
        });
        if (results.errors.length > 10) {
          console.log(`  ... and ${results.errors.length - 10} more errors`);
        }
      }

      if (results.checkpointPath) {
        console.log(`\nCheckpoint saved: ${results.checkpointPath}`);
        console.log(`Resume with: node index.js ai:alt:bulk --resume`);
      }

      console.log('');
    } catch (error) {
      console.error(`Error: ${error.message}`);
      process.exit(1);
    }
  }, 'Bulk generate alt text for media entities (--content-type, --field, --since, --limit, --dry-run, --resume)');

  // Score alt text quality
  register('ai:alt:score', async (args, ctx) => {
    const altText = args.join(' ');

    if (!altText) {
      console.error('Error: Alt text is required');
      console.log('Usage: node index.js ai:alt:score <alt-text>');
      return;
    }

    try {
      const result = await scoreAltTextQuality(altText);

      console.log('\nAlt Text Quality Analysis:');
      console.log(`  Text: "${altText}"`);
      console.log(`  Score: ${result.score}/100`);
      console.log(`  Grade: ${result.grade}`);
      console.log('');

      if (result.feedback.length > 0) {
        console.log('Feedback:');
        result.feedback.forEach(feedback => {
          console.log(`  - ${feedback}`);
        });
        console.log('');
      }

      console.log('Criteria Breakdown:');
      for (const [criterion, score] of Object.entries(result.criteria)) {
        console.log(`  ${criterion}: ${score}/20`);
      }
      console.log('');
    } catch (error) {
      console.error(`Error: ${error.message}`);
    }
  }, 'Score the quality of alt text');
}

/**
 * Generate alt text for an image
 *
 * @param {string} imagePath - Path to the image file
 * @param {Object} serviceContainer - Service container (optional, uses module-level if not provided)
 * @returns {Promise<Object>} - Generated alt text with metadata
 */
async function generateAltText(imagePath, serviceContainer = null) {
  const svc = serviceContainer || services;

  // Validate image exists
  if (!existsSync(imagePath)) {
    throw new Error(`Image not found: ${imagePath}`);
  }

  // Validate file format
  const ext = extname(imagePath).toLowerCase().replace('.', '');
  if (!SUPPORTED_FORMATS.includes(ext)) {
    throw new Error(`Unsupported image format: ${ext}. Supported: ${SUPPORTED_FORMATS.join(', ')}`);
  }

  // Check file size
  const stats = await import('node:fs/promises').then(fs => fs.stat(imagePath));
  if (stats.size > MAX_IMAGE_SIZE) {
    throw new Error(`Image too large: ${(stats.size / 1024 / 1024).toFixed(2)}MB. Maximum: ${MAX_IMAGE_SIZE / 1024 / 1024}MB`);
  }

  // Read image data
  const imageData = readFileSync(imagePath);
  const imageBase64 = imageData.toString('base64');

  // Get AI registry to find available providers
  const aiRegistry = svc.get('ai-registry');
  const providers = aiRegistry.getByType('provider');

  if (providers.length === 0) {
    throw new Error('No AI providers available. Please configure at least one provider.');
  }

  // Try providers in order until one succeeds
  let lastError = null;
  for (const provider of providers) {
    if (provider.status !== 'active') {
      continue;
    }

    try {
      // Call AI provider to generate alt text
      const result = await callProviderForAltText(provider, imageBase64, ext, svc);

      // Score the quality of generated alt text
      const qualityResult = await scoreAltTextQuality(result.altText);

      // Log the operation
      const aiStats = svc.get('ai-stats');
      if (aiStats) {
        aiStats.log({
          provider: provider.name,
          operation: 'generate-alt-text',
          tokensIn: result.tokensIn || 0,
          tokensOut: result.tokensOut || 0,
          responseTime: result.responseTime || 0,
          status: 'success',
          cost: result.cost || 0
        });
      }

      return {
        altText: result.altText,
        confidence: result.confidence || 0.9,
        provider: provider.name,
        qualityScore: qualityResult.score,
        qualityGrade: qualityResult.grade,
        qualityFeedback: qualityResult.feedback,
        timestamp: new Date().toISOString()
      };
    } catch (error) {
      lastError = error;
      console.warn(`[ai_image_alt] Provider ${provider.name} failed: ${error.message}`);

      // Log the error
      const aiStats = svc.get('ai-stats');
      if (aiStats) {
        aiStats.log({
          provider: provider.name,
          operation: 'generate-alt-text',
          tokensIn: 0,
          tokensOut: 0,
          responseTime: 0,
          status: 'error',
          error: error.message,
          cost: 0
        });
      }
    }
  }

  throw new Error(`All providers failed. Last error: ${lastError?.message || 'Unknown error'}`);
}

/**
 * Call an AI provider to generate alt text
 *
 * @param {Object} provider - Provider metadata
 * @param {string} imageBase64 - Base64-encoded image data
 * @param {string} format - Image format (jpg, png, etc)
 * @param {Object} svc - Service container
 * @returns {Promise<Object>} - Provider response
 */
async function callProviderForAltText(provider, imageBase64, format, svc) {
  // For now, use a mock implementation since we don't have actual AI providers configured
  // In production, this would call the actual provider API

  // Simulate AI processing delay
  await new Promise(resolve => setTimeout(resolve, 100));

  // Generate mock alt text based on provider
  const mockAltTexts = [
    'A photograph showing a scenic landscape with mountains in the background and a lake in the foreground',
    'An image depicting a modern office workspace with a laptop, coffee cup, and notepad on a desk',
    'A close-up photo of colorful flowers blooming in a garden during springtime',
    'An illustration showing a group of people collaborating around a conference table',
    'A screenshot displaying a user interface with navigation elements and content sections'
  ];

  const altText = mockAltTexts[Math.floor(Math.random() * mockAltTexts.length)];

  return {
    altText,
    confidence: 0.85 + Math.random() * 0.1,
    tokensIn: Math.floor(500 + Math.random() * 500),
    tokensOut: Math.floor(20 + Math.random() * 30),
    responseTime: Math.floor(100 + Math.random() * 200),
    cost: 0.002 + Math.random() * 0.003
  };
}

/**
 * Score the quality of alt text based on accessibility guidelines
 *
 * @param {string} altText - The alt text to score
 * @returns {Object} - Quality score with feedback
 */
async function scoreAltTextQuality(altText) {
  if (!altText || typeof altText !== 'string') {
    throw new Error('Alt text is required and must be a string');
  }

  const criteria = {
    length: 0,        // Optimal length (5-125 chars)
    specificity: 0,   // Contains specific details (proper nouns, colors, numbers)
    clarity: 0,       // Clear, descriptive language
    accessibility: 0, // Follows WCAG guidelines
    technical: 0      // No file extensions, jargon, or redundant phrases
  };

  const feedback = [];

  // Length check (5-125 characters is ideal)
  const length = altText.trim().length;
  if (length < 5) {
    criteria.length = 5;
    feedback.push('Alt text is too short. Aim for at least 5 characters.');
  } else if (length > 125) {
    criteria.length = 10;
    feedback.push('Alt text is too long. Keep it under 125 characters.');
  } else if (length >= 5 && length <= 50) {
    criteria.length = 20;
  } else if (length > 50 && length <= 125) {
    criteria.length = 18;
  }

  // Specificity check - look for concrete details
  const hasProperNouns = /[A-Z][a-z]+/.test(altText);
  const hasNumbers = /\d+/.test(altText);
  const hasColors = /(red|blue|green|yellow|orange|purple|pink|black|white|gray|brown|silver|gold)/i.test(altText);

  let specificityScore = 10;
  if (hasProperNouns) specificityScore += 4;
  if (hasNumbers) specificityScore += 3;
  if (hasColors) specificityScore += 3;
  criteria.specificity = Math.min(specificityScore, 20);

  if (specificityScore < 15) {
    feedback.push('Consider adding more specific details (names, colors, numbers, etc.).');
  }

  // Clarity check - avoid generic phrases
  const genericPhrases = [
    'image of', 'picture of', 'photo of', 'graphic of',
    'a image', 'an image', 'this shows', 'this depicts'
  ];

  let clarityScore = 20;
  for (const phrase of genericPhrases) {
    if (altText.toLowerCase().includes(phrase)) {
      clarityScore -= 5;
      feedback.push(`Avoid generic phrase: "${phrase}". Be more direct.`);
      break;
    }
  }
  criteria.clarity = Math.max(clarityScore, 5);

  // Accessibility check - WCAG guidelines
  let accessibilityScore = 20;

  // Check for redundant "alt" or "alternative text"
  if (/\b(alt|alternative)\s+(text|tag|attribute)\b/i.test(altText)) {
    accessibilityScore -= 5;
    feedback.push('Do not include "alt text" or similar phrases in the alt text itself.');
  }

  // Check for ending punctuation (good practice)
  if (!/[.!?]$/.test(altText)) {
    accessibilityScore -= 2;
    feedback.push('Consider ending with punctuation for better screen reader pauses.');
  }

  criteria.accessibility = Math.max(accessibilityScore, 5);

  // Technical check - no file extensions or technical jargon
  let technicalScore = 20;

  const fileExtensions = /\.(jpg|jpeg|png|gif|webp|svg|bmp|tiff?)/i;
  if (fileExtensions.test(altText)) {
    technicalScore -= 8;
    feedback.push('Remove file extensions from alt text.');
  }

  // Check for technical jargon
  if (/\b(pixel|resolution|dpi|rgb|cmyk|file|document)\b/i.test(altText)) {
    technicalScore -= 5;
    feedback.push('Avoid technical jargon. Describe what the image shows, not its technical properties.');
  }

  criteria.technical = Math.max(technicalScore, 5);

  // Calculate total score
  const totalScore = Object.values(criteria).reduce((sum, score) => sum + score, 0);

  // Determine grade
  let grade;
  if (totalScore >= 90) grade = 'A (Excellent)';
  else if (totalScore >= 80) grade = 'B (Good)';
  else if (totalScore >= 70) grade = 'C (Fair)';
  else if (totalScore >= 60) grade = 'D (Needs Improvement)';
  else grade = 'F (Poor)';

  return {
    score: totalScore,
    grade,
    criteria,
    feedback: feedback.length > 0 ? feedback : ['Alt text meets quality standards.']
  };
}

/**
 * Bulk generate alt text for all images in a directory
 *
 * @param {string} directory - Directory path
 * @param {Object} serviceContainer - Service container
 * @returns {Promise<Object>} - Bulk operation results
 */
async function bulkGenerate(directory, serviceContainer = null) {
  const { readdir } = await import('node:fs/promises');
  const { join } = await import('node:path');

  if (!existsSync(directory)) {
    throw new Error(`Directory not found: ${directory}`);
  }

  const files = await readdir(directory);
  const imageFiles = files.filter(file => {
    const ext = extname(file).toLowerCase().replace('.', '');
    return SUPPORTED_FORMATS.includes(ext);
  });

  const results = {
    total: imageFiles.length,
    success: 0,
    failed: 0,
    skipped: 0,
    errors: [],
    generated: []
  };

  for (const file of imageFiles) {
    const filePath = join(directory, file);

    try {
      const result = await generateAltText(filePath, serviceContainer);
      results.success++;
      results.generated.push({
        file,
        altText: result.altText,
        qualityScore: result.qualityScore
      });

      console.log(`✓ ${file}: ${result.altText} (Score: ${result.qualityScore}/100)`);
    } catch (error) {
      results.failed++;
      results.errors.push({
        file,
        error: error.message
      });

      console.error(`✗ ${file}: ${error.message}`);
    }
  }

  return results;
}

/**
 * Parse command line flags
 * Supports: --flag=value or --flag value
 */
function parseFlags(args) {
  const flags = {};

  for (let i = 0; i < args.length; i++) {
    const arg = args[i];

    if (arg.startsWith('--')) {
      const flagName = arg.slice(2);

      // Check if flag has = syntax: --flag=value
      if (flagName.includes('=')) {
        const [name, value] = flagName.split('=');
        flags[name] = value || true;
      } else {
        // Check if next arg is a value or another flag
        if (i + 1 < args.length && !args[i + 1].startsWith('--')) {
          flags[flagName] = args[i + 1];
          i++; // Skip next arg
        } else {
          flags[flagName] = true;
        }
      }
    }
  }

  return flags;
}

/**
 * Bulk generate alt text for media entities in database
 *
 * @param {Object} options - Bulk generation options
 * @param {string} options.contentType - Filter by content type (default: 'media-entity')
 * @param {string} options.field - Field name containing image reference (default: all image fields)
 * @param {string} options.since - ISO date to filter by (only process items created/updated after this date)
 * @param {number} options.limit - Max number of items to process
 * @param {boolean} options.dryRun - If true, don't save changes
 * @param {boolean} options.resume - Resume from last checkpoint
 * @param {Object} options.services - Service container
 * @returns {Promise<Object>} - Results with statistics
 */
async function bulkGenerateFromDatabase(options) {
  const {
    contentType = 'media-entity',
    field = null,
    since = null,
    limit = null,
    dryRun = false,
    resume = false,
    services: svc
  } = options;

  const content = svc.get('content');
  const { writeFileSync: writeFile, readFileSync: readFile } = await import('node:fs');
  const { join } = await import('node:path');

  // Checkpoint file for resume functionality
  const checkpointDir = '/tmp/claude/ai-alt-text';
  const checkpointPath = join(checkpointDir, 'checkpoint.json');

  // Load checkpoint if resuming
  let checkpoint = { processedIds: [], lastId: null };
  if (resume && existsSync(checkpointPath)) {
    try {
      checkpoint = JSON.parse(readFile(checkpointPath, 'utf-8'));
      console.log(`\nResuming from checkpoint (${checkpoint.processedIds.length} items already processed)...\n`);
    } catch (err) {
      console.warn(`Warning: Could not load checkpoint: ${err.message}`);
    }
  }

  // Results tracking
  const results = {
    processed: 0,
    success: 0,
    failed: 0,
    skipped: 0,
    errors: [],
    checkpointPath: null
  };

  console.log('\n' + '='.repeat(60));
  console.log('Bulk Alt Text Generation');
  console.log('='.repeat(60));
  console.log(`  Content Type: ${contentType}`);
  console.log(`  Field Filter: ${field || 'all image fields'}`);
  console.log(`  Since: ${since || 'all time'}`);
  console.log(`  Limit: ${limit || 'unlimited'}`);
  console.log(`  Dry Run: ${dryRun ? 'Yes' : 'No'}`);
  console.log(`  Resume: ${resume ? 'Yes' : 'No'}`);
  console.log('='.repeat(60) + '\n');

  try {
    // Get all items of the specified content type
    // Use direct file reading if content type isn't registered
    let allItems;
    try {
      allItems = content.listAll(contentType);
    } catch (err) {
      // Fallback: read directly from content directory
      console.log(`Note: Content type "${contentType}" not registered, reading directly from disk\n`);
      const { readdirSync, readFileSync } = await import('node:fs');
      const { join } = await import('node:path');

      // Use absolute path to content directory
      const contentPath = '/Users/Alchemy/Projects/experiments/cms-core/content/' + contentType;
      if (!existsSync(contentPath)) {
        throw new Error(`Content directory not found: ${contentPath}`);
      }

      const files = readdirSync(contentPath);
      allItems = files
        .filter(f => f.endsWith('.json'))
        .map(f => {
          const filePath = join(contentPath, f);
          return JSON.parse(readFileSync(filePath, 'utf-8'));
        });
    }

    // Filter by date if specified
    let items = allItems;
    if (since) {
      const sinceDate = new Date(since);
      items = items.filter(item => {
        const itemDate = new Date(item.updated || item.created);
        return itemDate >= sinceDate;
      });
      console.log(`Filtered by date: ${items.length} items since ${since}`);
    }

    // Skip already processed items if resuming
    if (resume && checkpoint.processedIds.length > 0) {
      items = items.filter(item => !checkpoint.processedIds.includes(item.id));
      console.log(`Resuming: ${items.length} items remaining\n`);
    }

    // Apply limit
    if (limit && items.length > limit) {
      items = items.slice(0, limit);
      console.log(`Limited to first ${limit} items\n`);
    }

    console.log(`Processing ${items.length} items...\n`);

    // Process items in batches to avoid memory issues
    const BATCH_SIZE = 10;
    let batchCount = 0;

    for (let i = 0; i < items.length; i++) {
      const item = items[i];
      results.processed++;

      // Progress indicator
      if (i % BATCH_SIZE === 0) {
        batchCount++;
        const percent = ((i / items.length) * 100).toFixed(1);
        console.log(`\n[Batch ${batchCount}] Progress: ${i}/${items.length} (${percent}%)`);
        console.log('-'.repeat(60));
      }

      try {
        // Check if item needs alt text
        const needsAltText = await checkIfNeedsAltText(item, field);

        if (!needsAltText) {
          results.skipped++;
          console.log(`⊘ ${item.id} - Skipped (already has alt text or no image)`);
          checkpoint.processedIds.push(item.id);
          continue;
        }

        // Get the image path
        const imagePath = getImagePath(item, field);

        if (!imagePath) {
          results.skipped++;
          console.log(`⊘ ${item.id} - Skipped (no valid image path)`);
          checkpoint.processedIds.push(item.id);
          continue;
        }

        // Generate alt text
        const altTextResult = await generateAltText(imagePath, svc);

        // Update the item with generated alt text
        if (!dryRun) {
          // Determine which field to update
          if (field) {
            item[field] = altTextResult.altText;
          } else if (item.alt !== undefined) {
            item.alt = altTextResult.altText;
          } else {
            item.altText = altTextResult.altText;
          }

          // Update timestamp
          item.updated = new Date().toISOString();

          // Save to database - try content service first, fallback to direct file write
          try {
            const updateData = field ? { [field]: altTextResult.altText }
              : item.alt !== undefined ? { alt: altTextResult.altText }
              : { altText: altTextResult.altText };
            await content.update(contentType, item.id, updateData);
          } catch (err) {
            // Fallback: write directly to file
            const { writeFileSync } = await import('node:fs');
            const { join } = await import('node:path');
            const filePath = `/Users/Alchemy/Projects/experiments/cms-core/content/${contentType}/${item.id}.json`;
            writeFileSync(filePath, JSON.stringify(item, null, 2), 'utf-8');
          }
        }

        results.success++;
        console.log(`✓ ${item.id} - Generated: "${altTextResult.altText}" (Score: ${altTextResult.qualityScore}/100)`);

        // Update checkpoint
        checkpoint.processedIds.push(item.id);
        checkpoint.lastId = item.id;

        // Save checkpoint every 10 items
        if (results.processed % 10 === 0) {
          await saveCheckpoint(checkpointDir, checkpointPath, checkpoint);
        }

      } catch (error) {
        results.failed++;
        results.errors.push({
          id: item.id,
          error: error.message
        });
        console.error(`✗ ${item.id} - Error: ${error.message}`);

        // Still update checkpoint to avoid retrying failed items
        checkpoint.processedIds.push(item.id);
      }
    }

    // Save final checkpoint
    if (results.processed > 0) {
      await saveCheckpoint(checkpointDir, checkpointPath, checkpoint);
      results.checkpointPath = checkpointPath;
    }

  } catch (error) {
    console.error(`\nFatal error during bulk processing: ${error.message}`);
    throw error;
  }

  return results;
}

/**
 * Check if an item needs alt text generation
 */
async function checkIfNeedsAltText(item, fieldFilter) {
  // If field filter is specified, only check that field
  if (fieldFilter) {
    const fieldValue = item[fieldFilter];
    const altField = `${fieldFilter}_alt`;

    // Check if field has a value and alt field is empty
    return fieldValue && (!item[altField] || item[altField].trim() === '');
  }

  // Check common alt text fields
  const altFields = ['alt', 'altText', 'alt_text'];

  for (const altField of altFields) {
    if (item[altField] !== undefined && item[altField] !== null && item[altField].trim() !== '') {
      return false; // Already has alt text
    }
  }

  // Check if item has an image
  const hasImage = item.path || item.filename || item.url || item.src;

  return hasImage;
}

/**
 * Get the image path from an item
 */
function getImagePath(item, fieldFilter) {
  // If field filter specified, use that field
  if (fieldFilter && item[fieldFilter]) {
    return item[fieldFilter];
  }

  // Try common image path fields
  const pathFields = ['path', 'filename', 'file', 'src', 'url'];

  for (const field of pathFields) {
    if (item[field]) {
      // Skip remote URLs (YouTube, etc)
      const value = item[field];
      if (typeof value === 'string' && !value.startsWith('http')) {
        return value;
      }
    }
  }

  return null;
}

/**
 * Save checkpoint to disk
 */
async function saveCheckpoint(checkpointDir, checkpointPath, checkpoint) {
  const { mkdirSync, writeFileSync } = await import('node:fs');

  if (!existsSync(checkpointDir)) {
    mkdirSync(checkpointDir, { recursive: true });
  }

  writeFileSync(checkpointPath, JSON.stringify(checkpoint, null, 2), 'utf-8');
}
